/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.51
 * Generated at: 2020-07-07 07:44:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1583283797094L));
    _jspx_dependants.put("/member/../header.jsp", Long.valueOf(1587196088947L));
    _jspx_dependants.put("jar:file:/C:/Users/USER/eclipse-workspace/WebExam40/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/exSample2/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/member/../footer.jsp", Long.valueOf(1585103981004L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>안은별의 포트폴리오</title>\r\n");
      out.write("\t<link href=\"css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css\">\r\n");
      out.write("\t<link href=\"css/common.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"css/mystyle.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/earlyaccess/nicomoji.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("    $(function(){\r\n");
      out.write("    \t\r\n");
      out.write("      $('.slider').bxSlider({\r\n");
      out.write("    \t  mode: 'fade',\r\n");
      out.write("    \t  captions: true\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      $(\".sitemap\").click(function() {\r\n");
      out.write("\t\t\t$(\".sitewrap\").slideDown();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t  $(\"#close\").click(function() {\r\n");
      out.write("\t\t\t$(\".sitewrap\").slideUp();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t  $(\".nav > nav > .navi > li\").hover(function() {\r\n");
      out.write("\t\t  $(this).children(\".navi2\").stop().slideDown();\r\n");
      out.write("\t  }, function() {\r\n");
      out.write("\t\t  $(this).children(\".navi2\").stop().slideUp();\r\n");
      out.write("\t  });\r\n");
      out.write("\t\t\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<div class=\"topnav\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t");

						if(session.getValue("user") == null){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"member?command=member_login\">ログイン</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"member?command=member_insert\">会員加入</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:void(0)\" class=\"sitemap\">サイト</a></li>\r\n");
      out.write("\t\t\t\t\t");

						}else{
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"member?command=member_logout\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:void(0)\" class=\"sitemap\">사이트맵</a></li>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"navigation\">\r\n");
      out.write("\t\t\t\t<h1 class=\"logo\"><a href=\"member?command=index\" style=\"text-decoration: none;\">ホシナのサイト</a></h1>\r\n");
      out.write("\t\t\t\t<div class=\"nav\">\r\n");
      out.write("\t\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"navi\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"about?command=about\"> ご紹介</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"navi2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"about?command=about_profile\">履歴書</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">自己紹介書</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">資格証</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"port?command=port_web\">ポートフォリオ</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"navi2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"port?command=port_web\">ウェブ開発</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"ui?command=ui_index\">UIデザイン</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"qa?command=qa_index\">フリーボード</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"navi2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"qa?command=qa_index\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"guest?command=guest_index\">芳名録</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"diary.do\">日記</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"navi2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">就職日記</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">開発日記</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"contact.do\">CONTACT</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"line\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"sitewrap\">\r\n");
      out.write("\t\t<span class=\"fa fa-close\" id=\"close\" style=\"cursor:pointer\"></span>\r\n");
      out.write("\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t<span class=\"map\">내소개</span>\r\n");
      out.write("\t\t\t<span class=\"map\">포트폴리오</span>\r\n");
      out.write("\t\t\t<span class=\"map\">자유게시판</span>\r\n");
      out.write("\t\t\t<span class=\"map\">내일기</span>\r\n");
      out.write("\t\t\t<span class=\"map\">CONTACT</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"contain\">\r\n");
      out.write("\t<div class=\"sub-topcontent\">\r\n");
      out.write("\t\t<h2 class=\"sub-title\">회원가입</h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"write-form\">\r\n");
      out.write("\t\t<table summery=\"회원가입 글쓰기 테이블 입니다\">\r\n");
      out.write("\t\t\t<caption class=\"readonly\">회원가입 입력폼</caption>\t\t\t\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t<col width=\"80%\">\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t<form name=\"membe\" method=\"post\" action=\"member\">\r\n");
      out.write("\t\t\t<input type = \"hidden\" name = \"command\" value = \"member_insert_pro\">\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend class=\"readonly\">입력폼</legend>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"id\">아이디 <b>필수입력</b></label>\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"userid\" id=\"id\" class=\"minput\"> \r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width:8%; float:right;padding:10px;\r\n");
      out.write("\t\t\t\t\t\t\theight:50px; margin-top:3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"중복확인\" alt=\"중복확인\"  onClick = \"return formcheck()\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"background: #FF4000; color:#fff;\r\n");
      out.write("\t\t\t\t\t\t\twidth:100%; height:100%; border:0 none; cursor:pointer;\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\"><lavel for=\"pass1\">패스워드</lavel></th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" name=\"pwd\" id=\"pass1\" class=\"minput\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\">패스워드 확인</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" name=\"repwd\" class=\"minput\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\">이름</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"name\" class=\"minput\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><label for=\"phone\">전화번호<span class=\"must\"></span></label></th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"phone\" id=\"phone\" class=\"minput\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"tc_point\"> &nbsp;&nbsp;xxx-xxxx-xxxx의 형식을 맞춰주세요.</span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\">이메일</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"em\" class=\"minput\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"전송\" class=\"btn-write\" onclick=\"formcheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"목록\"  class=\"btn-reset\" onclick=\"javascript:location.href='member?command=index'\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction formcheck() {\r\n");
      out.write("\t\t//아이디 유효성\r\n");
      out.write("\t\tvar puserid = /^[a-z0-9]{5,14}$/; //영문,숫자 5~14자\r\n");
      out.write("\t\tvar userid = membe.userid.value;\r\n");
      out.write("\t\tif(userid==\"\"){\r\n");
      out.write("\t\t\talert(\"아이디를 입력해주세요.\");\r\n");
      out.write("\t\t\tmembe.userid.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!userid.match(puserid)){\r\n");
      out.write("\t\t\talert(\"아이디 형식을 맞춰주세요.\");\r\n");
      out.write("\t\t\tmembe.userid.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//비밀번호 유효성\r\n");
      out.write("\t\tvar pwd = membe.pwd.value;\r\n");
      out.write("\t\tif (pwd == \"\") {\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력해주세요..\");\r\n");
      out.write("\t\t\tmembe.pwd.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar pattern1 = /[0-9]/; // 숫자 \r\n");
      out.write("\t\tvar pattern2 = /[a-zA-Z]/; // 문자\r\n");
      out.write("\t\tvar pattern3 = /[~!@#$%^&*()_+|<>?:{}]/; // 특수문자\r\n");
      out.write("\t\tif (pwd.match(pattern1)){\r\n");
      out.write("\t\t\tif(pwd.match(pattern2)){\r\n");
      out.write("\t\t\t\tif(pwd.match(pattern3)){\r\n");
      out.write("\t\t\t\t\tif(pwd.length>8 && pwd.length< 14 ){\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert(\"비밀번호는 특수문자,숫자,영문 조합으로 9~13자로 작성해 주십시오.\");\r\n");
      out.write("\t\t\t\t\t\tmembe.pwd.focus();\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"비밀번호는 특수문자,숫자,영문 조합으로 9~13자로 작성해 주십시오.\");\r\n");
      out.write("\t\t\t\t\tmembe.pwd.focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(\"비밀번호는 특수문자,숫자,영문 조합으로 9~13자로 작성해 주십시오.\");\r\n");
      out.write("\t\t\t\tmembe.pwd.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"비밀번호는 특수문자,숫자,영문 조합으로 9~13자로 작성해 주십시오.\");\r\n");
      out.write("\t\t\tmembe.pwd.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t//비밀번호 확인 유효성\r\n");
      out.write("\r\n");
      out.write("\t\tvar repwd=membe.repwd.value;\r\n");
      out.write("\t\tif(repwd==\"\"){\r\n");
      out.write("\t\t\tmembe.repwd.value=membe.pwd.value;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(repwd != \"\"){\r\n");
      out.write("\t\t\tif(repwd!=pwd){\r\n");
      out.write("\t\t\talert(\"입력한 비밀번호가 같지 않습니다\");\r\n");
      out.write("\t\t\tmembe.repwd.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//이름 유효성\r\n");
      out.write("\t\tvar pname = /^[가-힣]{2,8}$/; //한글만 입력 2~8자\r\n");
      out.write("\t\tvar name = membe.name.value;\r\n");
      out.write("\t\tif(name==\"\"){\r\n");
      out.write("\t\t\talert(\"이름을 입력해주세요.\");\r\n");
      out.write("\t\t\tmembe.name.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!name.match(pname)){\r\n");
      out.write("\t\t\talert(\"이름 형식을 맞춰주세요.\");\r\n");
      out.write("\t\t\tmembe.name.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t//전화번호 유효성\r\n");
      out.write("\t\tvar pphone = /^01(?:0|1|[6-9])-(?:\\d{3}|\\d{4})-\\d{4}$/;\r\n");
      out.write("\t\tvar phone = membe.phone.value;\r\n");
      out.write("\t\tif (phone == \"\") {\r\n");
      out.write("\t\t\talert(\"전화번호를 입력해주세요.\");\r\n");
      out.write("\t\t\tmembe.phone.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!phone.match(pphone)){\r\n");
      out.write("\t\t\talert(\"전화번호 형식을 맞춰주세요.\");\r\n");
      out.write("\t\t\tmembe.phone.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t//이메일 유효성\r\n");
      out.write("\t\tvar pemail = /^[0-9a-zA-Z]([-_\\.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_\\.]?[0-9a-zA-Z])*\\.[a-zA-Z]{2,3}$/i;\r\n");
      out.write("\t\tvar email = membe.em.value;\r\n");
      out.write("\t\tif (email == \"\") {\r\n");
      out.write("\t\t\talert(\"이메일을 입력해주세요.\");\r\n");
      out.write("\t\t\tmembe.email.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!email.match(pemail)){\r\n");
      out.write("\t\t\talert(\"이메일 형식을 맞춰주세요.\");\r\n");
      out.write("\t\t\tmembe.email.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\talert(\"등록하시겠습니까?\");\r\n");
      out.write("\t\tmembe.submit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<p>&copy; EUNBYUL. All &nbsp;&nbsp;Rights Reserved.</p>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\t<!-- &copy; &nbsp; &gt; > &lt;< -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
